In [3]:
    import torch

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1
y.backward()  # Compute gradients
print(x.grad)  # dy/dx = 2x + 3 --> at x=2, it should be 7

None
tensor(7.)


In [5]:
# tensor is also type of matrix,why we are using tensor when we have numpy ???
#because it run on gpu ,numpy runs on cpu

In [7]:
pip install torchvision 
#pip install torch 

   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.7 MB 3.2 MB/s eta 0:00:01
   - -------------------------------------- 0.1/1.7 MB 3.2 MB/s eta 0:00:01
   - -------------------------------------- 0.1/1.7 MB 3.2 MB/s eta 0:00:01
   -- ------------------------------------- 0.1/1.7 MB 656.4 kB/s eta 0:00:03
   --- ------------------------------------ 0.2/1.7 MB 893.0 kB/s eta 0:00:02
   --- ------------------------------------ 0.2/1.7 MB 893.0 kB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.7 MB 583.1 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/1.7 MB 565.6 kB/s eta 0:00:03
   ----- ---------------------------------- 0.2/1.7 MB 573.4 kB/s eta 0:00:03
   ------- -------------------------------- 0.3/1.7 MB 749.8 kB/s eta 0:00:02
   ---------- ----------------------------- 0.4/1.7 MB 867.4 kB/s eta 0:00:02
   ---------- ----------------------------- 0.4/1.7 MB 867.4 kB/s eta 0:00:02
 

  You can safely remove it manually.


In [9]:
pip install torchaudio


   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   ---------------------------------------- 0.0/2.5 MB 217.9 kB/s eta 0:00:12
   - --------------------------

In [1]:
import torch
x= torch.empty(1)# 1d 
y=torch.empty(2,3)# used to intialise near to 0 value
print(x)
print(y)

tensor([-1.2683e+30])
tensor([[-1.2776e+30,  1.0580e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [37]:
print(torch.zeros(1,3))
print(torch.ones(3,4))
print(torch.rand(3,6))
print(torch.ones(1,1,dtype=int))



tensor([[0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.4409, 0.7603, 0.1194, 0.1917, 0.1227, 0.8156],
        [0.3960, 0.8811, 0.8045, 0.6643, 0.9154, 0.9054],
        [0.3176, 0.2338, 0.4976, 0.0123, 0.1638, 0.9018]])
tensor([[1]])


In [151]:
# basic operation 
x= torch.rand(3,3)# 1d 
y=torch.rand(3,3)
print(torch.add(x,y))
print(torch.sub(x,y))
print(torch.mul(x,y))


tensor([[0.5637, 1.2316, 1.3591],
        [1.5181, 1.1211, 1.8526],
        [0.3759, 1.7504, 1.6511]])
tensor([[ 0.3674,  0.5737, -0.2569],
        [ 0.3464,  0.4175, -0.0731],
        [-0.0716,  0.0555,  0.0878]])
tensor([[0.0457, 0.2969, 0.4453],
        [0.5462, 0.2706, 0.8567],
        [0.0341, 0.7652, 0.6796]])


In [145]:
# lets perform slicing on tensor to print only first row
print(x)
print(x[:1])
# to print coloumn 
print(x[:,0])# first coloumn
print(x[:,1])#sencond coloumn

tensor([[0.8823, 0.3746, 0.1458],
        [0.3671, 0.5645, 0.5272],
        [0.1141, 0.0992, 0.1637]])
tensor([[0.8823, 0.3746, 0.1458]])
tensor([0.8823, 0.3671, 0.1141])
tensor([0.3746, 0.5645, 0.0992])


In [147]:
# to resize tensor
x= torch.rand(4,4)
print(x)
y=x.view(16)# to print in 1D
print(y)

tensor([[0.7171, 0.2488, 0.4384, 0.8215],
        [0.5741, 0.7075, 0.4120, 0.8646],
        [0.2945, 0.6296, 0.8637, 0.4373],
        [0.5454, 0.2737, 0.2903, 0.3664]])
tensor([0.7171, 0.2488, 0.4384, 0.8215, 0.5741, 0.7075, 0.4120, 0.8646, 0.2945,
        0.6296, 0.8637, 0.4373, 0.5454, 0.2737, 0.2903, 0.3664])


In [73]:
# to convert from torch to numpy
import numpy as np
z=x.numpy()
print(z)

[[0.9756571  0.8678842  0.37409693 0.67257816]
 [0.8888939  0.8316888  0.9417459  0.53168476]
 [0.46634507 0.94891703 0.44822854 0.7994761 ]
 [0.77397436 0.5277369  0.10012776 0.39898294]]


In [75]:
# to check the whether tensor is on gpu or cpu
print(x.device)

cpu


In [87]:
# from numpy to tensor
a=np.arange(0,20,2)
print(a)
a=a.reshape(5,2)
print(a)
b=torch.from_numpy(a)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]], dtype=torch.int32)


In [91]:
# if we created a tensor using numpy, then any modification made to matrix will makes change automatically in the tensor
a[0,0]=1
print(a)
print(b)

[[ 1  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
tensor([[ 1,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]], dtype=torch.int32)


In [105]:
# diff b/w torch.tensor and Torch.Tensor
l=[1,2,3,4,5,6,7]
t=torch.tensor(l)
print(t.dtype)
T=torch.Tensor(l)
print(T.dtype)

torch.int64
torch.float32


In [111]:
# to reduce memory size
x=torch.zeros(4,5,dtype=torch.int32)

In [119]:
# arange function
l=torch.arange(0,20,2).reshape(5,2)
l


tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18]])

In [125]:
l=torch.linspace(5,5,10)# start ,end,how many eql parts
l

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [129]:
# if we want to create tensor for normal distribution use randn function
x=torch.randn(5,3)
x

tensor([[-2.4185e-01,  1.1532e+00,  1.1289e-01],
        [ 9.8321e-01, -2.7611e-01,  1.8539e+00],
        [-1.5680e+00,  5.6473e-01, -3.7391e-01],
        [ 1.1897e+00,  1.7244e+00, -3.6968e-04],
        [ 1.4770e+00,  7.5353e-01, -7.9276e-01]])

In [141]:
# this random function will generate new values every time when we run the code to avoid this we use manual seed function,it will helps to get same values every time
torch.manual_seed(101)
x=torch.rand(5,4)
x

tensor([[0.1980, 0.4503, 0.0909, 0.8872],
        [0.2894, 0.0186, 0.9095, 0.3406],
        [0.4309, 0.7324, 0.4776, 0.0716],
        [0.5834, 0.7521, 0.7649, 0.1443],
        [0.7152, 0.3953, 0.6244, 0.3684]])

In [153]:
# dimensions and shape 
print(x.shape)
print(x.ndim)

torch.Size([3, 3])
2


In [3]:
l=torch.tensor([1,2,3,4])
# to reverse a tensor 
print(l.flip(x,dims=[0]))

TypeError: flip(): argument 'dims' (position 1) must be tuple of ints, but found element of type Tensor at pos 0

In [ ]:
What  is tensor ?
tensors is a specialised multi dimensional array designed for mathematical and computational efficiency
2d tensor -->black and white img
3d tensor -->rgb image 
4d tensor -->batches of rgb images (10 rgb imgs)[32, 128(r), 128(g), 3(b)] "where 32 indicates no of rgb image"
5d tensor -->video data


why tensor are used in dl?
we can perform common mathematical operations easily like add ,mul,dot product
data like images ,audio,video text can be rep as tensor
  ie : image can be rep as 3d tensor
efficent computation since it uses gpus



where are tensors used in deep learning?
1 data storage --> training data (img,txt etc.)can store in tensor
2 weight and bias can be stored easily by using tensors 
3 matrix operations


In [5]:
if torch.cuda.is_available():
    print("gpu")
else:
    print("cpu")

cpu


In [23]:
e=torch.randint(size=(2,3),low=0,high=20,dtype=torch.float32)
e

tensor([[19.,  6., 16.],
        [11., 11., 12.]])

In [25]:
torch.sum(e)

tensor(75.)

In [27]:
torch.abs(e)

tensor([[19.,  6., 16.],
        [11., 11., 12.]])

In [29]:
torch.neg(e)

tensor([[-19.,  -6., -16.],
        [-11., -11., -12.]])

In [33]:
torch.mean(e,dim=0)

tensor([15.0000,  8.5000, 14.0000])

In [35]:
torch.max(e)

tensor(19.)

In [37]:
torch.prod(e)

tensor(2648448.)

In [39]:
#stadard deviation
torch.std(e)

tensor(4.5056)

In [41]:
# to get minimum value position
torch.argmin(e)
#torch.argmax(e)

tensor(1)

In [43]:
#variance 
torch.var(e)

tensor(20.3000)

In [45]:
'''matrix operations'''

'matrix operation'

In [55]:
torch.manual_seed(32)
f = torch.randint(size =(2,3),low=1, high=10 ,dtype=torch.int16)
g= torch.randint(size =(3,2),low=1, high=10 ,dtype=torch.int16)

In [57]:
print(f)
print(g)

tensor([[2, 9, 4],
        [7, 8, 7]], dtype=torch.int16)
tensor([[4, 9],
        [3, 1],
        [5, 8]], dtype=torch.int16)


In [59]:
#matrix mul
torch.matmul(f,g)

tensor([[ 55,  59],
        [ 87, 127]], dtype=torch.int16)

In [71]:
vector1= torch.tensor([1,2])
vector2= torch.tensor([1,2])

In [73]:
torch.dot(vector1,vector2)

tensor(5)

In [75]:
#transpose
f


tensor([[2, 9, 4],
        [7, 8, 7]], dtype=torch.int16)

In [77]:
torch.transpose(f,0,1)

tensor([[2, 7],
        [9, 8],
        [4, 7]], dtype=torch.int16)

In [97]:

h= torch.randint(size =(3,3),low=1, high=10 ,dtype=torch.float32)
h


tensor([[3., 2., 8.],
        [3., 1., 4.],
        [3., 3., 4.]])

In [99]:
#det
torch.det(h)

tensor(24.)

In [101]:
# inverse
torch.inverse(h)

tensor([[-0.3333,  0.6667,  0.0000],
        [ 0.0000, -0.5000,  0.5000],
        [ 0.2500, -0.1250, -0.1250]])

In [ ]:
## comparision operation

In [111]:
torch.manual_seed(48)
i = torch.randint(size =(2,3),low=1, high=10 ,dtype=torch.int16)
j= torch.randint(size =(2,3),low=1, high=10 ,dtype=torch.int16)

In [113]:
i

tensor([[9, 1, 1],
        [2, 8, 3]], dtype=torch.int16)

In [115]:
j

tensor([[5, 9, 2],
        [3, 3, 5]], dtype=torch.int16)

In [117]:
#greater tha
i>j

tensor([[ True, False, False],
        [False,  True, False]])

In [119]:
#less than
i<j

tensor([[False,  True,  True],
        [ True, False,  True]])

In [121]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [123]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [129]:
#special functions
k=torch.randint(size=(2,3),low=0,high=10)
k


tensor([[2, 9, 6],
        [3, 2, 8]])

In [131]:
#log
torch.log(k)

tensor([[0.6931, 2.1972, 1.7918],
        [1.0986, 0.6931, 2.0794]])

In [135]:
torch.sqrt(k)

tensor([[1.4142, 3.0000, 2.4495],
        [1.7321, 1.4142, 2.8284]])

In [137]:
torch.sigmoid(k)

tensor([[0.8808, 0.9999, 0.9975],
        [0.9526, 0.8808, 0.9997]])

In [143]:
torch.softmax(h,dim=0)

tensor([[0.3333, 0.2447, 0.9647],
        [0.3333, 0.0900, 0.0177],
        [0.3333, 0.6652, 0.0177]])

In [145]:
torch.relu(k)

tensor([[2, 9, 6],
        [3, 2, 8]])

In [147]:
#implace operations
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9095, 0.2975, 0.3869],
        [0.9720, 0.7859, 0.6194]])
tensor([[0.7426, 0.4886, 0.1987],
        [0.1433, 0.3335, 0.8004]])


In [149]:
m+n

tensor([[1.6521, 0.7861, 0.5857],
        [1.1153, 1.1194, 1.4198]])

In [151]:
#implace is used to stored in the particualar variable it self 
m.add_(n)

tensor([[1.6521, 0.7861, 0.5857],
        [1.1153, 1.1194, 1.4198]])

In [153]:
m

tensor([[1.6521, 0.7861, 0.5857],
        [1.1153, 1.1194, 1.4198]])

In [155]:
m.relu_()

tensor([[1.6521, 0.7861, 0.5857],
        [1.1153, 1.1194, 1.4198]])

In [157]:
m

tensor([[1.6521, 0.7861, 0.5857],
        [1.1153, 1.1194, 1.4198]])

In [159]:
# copying tensor
a=torch.rand(2,3)
a

tensor([[0.9047, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [163]:
b=a
b

tensor([[0.9047, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [165]:
a[0][0]=0

In [167]:
a

tensor([[0.0000, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [169]:
b

tensor([[0.0000, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [171]:
# by using above method if we made changes in original tensor will reflects to the copy 

In [173]:
# by using clone function we can avoid those
b=a.clone()
b

tensor([[0.0000, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [175]:
a[0][0]=21
a

tensor([[21.0000,  0.8434,  0.6618],
        [ 0.8133,  0.8181,  0.4208]])

In [177]:
b

tensor([[0.0000, 0.8434, 0.6618],
        [0.8133, 0.8181, 0.4208]])

In [233]:
#memory loc 
id(a)

2806777077136

In [181]:
id(b)

2806777777232

In [183]:
# since both memory locations are diff copying can be donr properly


In [185]:
#reshapping tensors
q=torch.zeros(4,4)

In [187]:
q.reshape(2,2,2,2)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [191]:
#flatten -->1d
q.flatten()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
#unsqueez
b=torch.rand(2,3,3)
b

tensor([[[0.1378, 0.6450, 0.6217],
         [0.7962, 0.6872, 0.6427],
         [0.5766, 0.6628, 0.5661]],

        [[0.3093, 0.1823, 0.1479],
         [0.4419, 0.4507, 0.9691],
         [0.0213, 0.1072, 0.3413]]])

In [215]:
b.unsqueeze(1).shape

torch.Size([2, 1, 3, 3])

### AUTOGRAD

### Autograd is a core component to compute differentuation pf pytorch thar providea automatic diff for tensor operation .it enables gradient computation,which is essential for ml models used for optimization like gradient descent   

In [221]:
import torch

In [223]:
x=torch.tensor(3.0,requires_grad=True)

In [225]:
y=x**2

In [227]:
print(x)

tensor(3., requires_grad=True)


In [231]:
print(y) # now it automatically computed the gradient value

tensor(9., grad_fn=<PowBackward0>)


In [235]:
y.backward()

In [239]:
x.grad

tensor(6.)

##### example 2 y=x**2 ,z=sin(y)

In [253]:
# we check this example result manully
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [289]:
dz_dx(3)

-5.466781571308061

In [277]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2
z=torch.sin(y)

In [279]:
x

tensor(3., requires_grad=True)

In [281]:
y

tensor(9., grad_fn=<PowBackward0>)

In [283]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [285]:
z.backward(retain_graph=True)


In [287]:
x.grad

tensor(-5.4668)

In [291]:
y.grad

C:\Users\eedim\AppData\Local\Temp\ipykernel_11356\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


# More on Computational Graphs

Conceptually, autograd keeps a record of data (tensors) and all executed operations (along with the resulting new tensors) in a directed acyclic graph (DAG) consisting of Function objects. In this DAG, leaves are the input tensors, roots are the output tensors.

By tracing this graph from roots to leaves, you can automatically compute the gradients using the chain rulg

In a forward pass, autograd does two things simultaneously:

⚫ run the requested operation to compute a resulting tensor

maintain the operation's gradient function in the DAG.

The backward pass kicks off when backward() is called on the DAG root. autograd then:

computes the gradients from each.grad_fn,

accumulates them in the respective tensor's grad attribute

using the chain rule, propagates all the way to the leaf tensors.

# example 3 this is the netural network
x -------w------------------>sigmoid -------------------y_hat----------->loss
linear Transformation 
            z=w.x+b
activation function
            ypred=σ(z)=1/(1+e**-z)
loss function 
  l=-[ytarget.ln(ypred)+(1-ypred).ln(1-ypred)

In [9]:
import torch
x=torch.tensor(6.7,requires_grad=True)  # input
y=torch.tensor(0.0,requires_grad=True)  # true lable
w=torch.tensor(1.0,requires_grad=True)#weight
b=torch.tensor(0.0,requires_grad=True)

In [10]:
x

tensor(6.7000, requires_grad=True)

In [11]:
y

tensor(0., requires_grad=True)

In [12]:
w

tensor(1., requires_grad=True)

In [17]:
b

tensor(0., requires_grad=True)

In [19]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [21]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [23]:
def binary_cross_entropy_loss (prediction, target):
    epsilon=1e-8 # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1-epsilon)
    return (target*torch.log(prediction) + (1-target)*torch.log(1+prediction))

In [28]:
loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(0.6925, grad_fn=<AddBackward0>)

In [30]:
loss.backward()

In [32]:
w.grad

tensor(0.0041)

In [34]:
b.grad

tensor(0.0006)

In [36]:
x.grad

tensor(0.0006)

In [38]:
y.grad

tensor(-0.6938)

In [65]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [84]:
# vector 
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

y=(x**2).mean()
y


In [89]:
y.backward(retain_graph=True)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [91]:
x.grad.zero_()

AttributeError: 'NoneType' object has no attribute 'zero_'

In [91]:
x.grad.zero_()

AttributeError: 'NoneType' object has no attribute 'zero_'

###loading a dataset
###basic preprocessing
###training process
###a)creating a model
###b)forward pass
###c)loss calculation
###d)backprop
###e)parameter update
###model evalutaion

### breast cancer proj

In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder 

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.describe

<bound method NDFrame.describe of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181

In [9]:
df.isnull

<bound method DataFrame.isnull of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181

In [11]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [13]:
df.shape

(569, 33)

In [15]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)


In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

#### train test split

In [20]:
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
230        17.05         19.08          113.40      895.0          0.11410   
237        20.48         21.46          132.50     1306.0          0.08355   
153        11.15         13.08           70.87      381.9          0.09754   
274        17.93         24.48          115.20      998.9          0.08855   
67         11.31         19.04           71.80      394.1          0.08139   
..           ...           ...             ...        ...              ...   
546        10.32         16.35           65.31      324.9          0.09434   
157        16.84         19.46          108.40      880.2          0.07445   
115        11.93         21.53           76.53      438.6          0.09768   
461        27.42         26.27          186.90     2501.0          0.10840   
495        14.87         20.21           96.12      680.9          0.09587   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
230           0.15720         0.19100             0.109000         0.2131   
237           0.08348         0.09042             0.060220         0.1467   
153           0.05113         0.01982             0.017860         0.1830   
274           0.07027         0.05699             0.047440         0.1538   
67            0.04701         0.03709             0.022300         0.1516   
..                ...             ...                  ...            ...   
546           0.04994         0.01012             0.005495         0.1885   
157           0.07223         0.05150             0.027710         0.1844   
115           0.07849         0.03328             0.020080         0.1688   
461           0.19880         0.36350             0.168900         0.2061   
495           0.08345         0.06824             0.049510         0.1487   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
230                 0.06325  ...         19.59          24.89   
237                 0.05177  ...         24.22          26.17   
153                 0.06105  ...         11.99          16.30   
274                 0.05510  ...         20.92          34.69   
67                  0.05667  ...         12.33          23.84   
..                      ...  ...           ...            ...   
546                 0.06201  ...         11.25          21.77   
157                 0.05268  ...         18.22          28.07   
115                 0.06194  ...         13.67          26.15   
461                 0.05623  ...         36.04          31.37   
495                 0.05748  ...         16.01          28.48   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
230           133.50      1189.0           0.17030            0.39340   
237           161.70      1750.0           0.12280            0.23110   
153            76.25       440.8           0.13410            0.08971   
274           135.10      1320.0           0.13150            0.18060   
67             78.00       466.7           0.12900            0.09148   
..               ...         ...               ...                ...   
546            71.12       384.9           0.12850            0.08842   
157           120.30      1032.0           0.08774            0.17100   
115            87.54       583.0           0.15000            0.23990   
461           251.20      4254.0           0.13570            0.42560   
495           103.90       783.6           0.12160            0.13880   

     concavity_worst  concave points_worst  symmetry_worst  \
230          0.50180               0.25430          0.3109   
237          0.31580               0.14450          0.2238   
153          0.07116               0.05506          0.2859   
274          0.20800               0.11360          0.2504   
67           0.14440               0.06961          0.2400   
..               ...                   ...             ...   
546          0.04384               0.02381         

In [24]:
y_train

230    M
237    M
153    B
274    M
67     B
      ..
546    B
157    B
115    B
461    M
495    B
Name: diagnosis, Length: 455, dtype: object

In [35]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_train
X_test=scaler.transform(X_test)
X_test

C:\Users\eedim\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


array([[9.405e+00, 2.170e+01, 5.960e+01, ..., 3.770e-02, 2.872e-01,
        8.304e-02],
       [1.462e+01, 2.402e+01, 9.457e+01, ..., 6.946e-02, 2.522e-01,
        7.246e-02],
       [1.171e+01, 1.667e+01, 7.472e+01, ..., 6.968e-02, 1.712e-01,
        7.343e-02],
       ...,
       [1.218e+01, 1.784e+01, 7.779e+01, ..., 5.882e-02, 2.227e-01,
        7.376e-02],
       [1.174e+01, 1.469e+01, 7.631e+01, ..., 1.056e-01, 2.604e-01,
        9.879e-02],
       [1.894e+01, 2.131e+01, 1.236e+02, ..., 1.789e-01, 2.551e-01,
        6.589e-02]])

In [37]:
y_train

230    M
237    M
153    B
274    M
67     B
      ..
546    B
157    B
115    B
461    M
495    B
Name: diagnosis, Length: 455, dtype: object

In [43]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,

In [45]:
y_test=encoder.transform(y_test)
y_test

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [59]:
X_train_tensor=torch.from_numpy(X_train)
X_train_tensor

tensor([[ 0.8249, -0.0819,  0.8766,  ...,  2.1629,  0.3322,  0.3540],
        [ 1.8058,  0.4623,  1.6681,  ...,  0.4633, -1.1081, -0.7164],
        [-0.8624, -1.4540, -0.8858,  ..., -0.9212, -0.0812, -0.9129],
        ...,
        [-0.6393,  0.4783, -0.6513,  ..., -0.6517, -0.7773,  0.0662],
        [ 3.7905,  1.5622,  3.9224,  ...,  2.2898, -0.4417, -0.5504],
        [ 0.2014,  0.1765,  0.1605,  ..., -0.1993, -0.8914, -1.0086]],
       dtype=torch.float64)

In [53]:
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)
X_test_tensor=torch.from_numpy(X_test)

In [57]:
y_train_tensor

tensor([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,

## Defining the model


In [104]:
class my_simple_nn():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)
    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self,y_pred,y):
         epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

    



### Important parameter

In [91]:
learning_rate=0.1
epochs=25

### training pipeline

In [114]:
# create model
model =my_simple_nn(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.1172241998908286
Epoch: 2, Loss: 4.01923101708565
Epoch: 3, Loss: 3.9149697988349987
Epoch: 4, Loss: 3.806967448820282
Epoch: 5, Loss: 3.695776403499818
Epoch: 6, Loss: 3.5781799247289237
Epoch: 7, Loss: 3.4557132941348487
Epoch: 8, Loss: 3.3277374256030106
Epoch: 9, Loss: 3.1963312885973507
Epoch: 10, Loss: 3.0654639852058807
Epoch: 11, Loss: 2.9333288385868714
Epoch: 12, Loss: 2.797438986172446
Epoch: 13, Loss: 2.6544152107602836
Epoch: 14, Loss: 2.5142361337185077
Epoch: 15, Loss: 2.3772411976620513
Epoch: 16, Loss: 2.2446813021556156
Epoch: 17, Loss: 2.11371809066309
Epoch: 18, Loss: 1.9831898325266402
Epoch: 19, Loss: 1.8505083372637088
Epoch: 20, Loss: 1.7242870353318167
Epoch: 21, Loss: 1.6063739154884615
Epoch: 22, Loss: 1.498251261100587
Epoch: 23, Loss: 1.3983185051703508
Epoch: 24, Loss: 1.3083931779266418
Epoch: 25, Loss: 1.228203815180945


In [116]:
model.bias

tensor([0.3529], dtype=torch.float64, requires_grad=True)

In [118]:
model.weights

tensor([[ 0.2273],
        [-0.0063],
        [-0.0134],
        [-0.3503],
        [-0.1922],
        [ 0.1656],
        [ 0.0822],
        [-0.2841],
        [ 0.4521],
        [ 0.1382],
        [-0.3250],
        [ 0.6015],
        [ 0.3740],
        [ 0.3603],
        [ 0.4409],
        [-0.0796],
        [ 0.5500],
        [-0.1351],
        [ 0.6180],
        [-0.0796],
        [-0.0591],
        [ 0.1632],
        [-0.1518],
        [ 0.3009],
        [ 0.3834],
        [ 0.3455],
        [-0.5192],
        [ 0.2884],
        [ 0.5010],
        [ 0.1312]], dtype=torch.float64, requires_grad=True)

# evaluation

In [121]:
#model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.449984610080719


# nn module in pytorch
plan of action


1) revision

2) improvement

3) the nn module

4) the torch.optim module

6) creating simple architecture:


7) n1-------------
   n2------------
   .                   Sigmoid function ----------------->output
   .
   nn-----------





In [1]:
import torch
import torch.nn as nn

In [26]:
class Model(nn.Module):#inherite from nn.module class
    def __init__(self,num_feature):
        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        z=self.linear(features)
        z=self.sigmoid(z)
        
        return z

In [28]:
# creating a dataset
features=torch.rand(10,5)
#creating model
model=Model(features.shape[1])
model.forward(features)

tensor([[0.4352],
        [0.4025],
        [0.4501],
        [0.4412],
        [0.3732],
        [0.3842],
        [0.4266],
        [0.4575],
        [0.4845],
        [0.4504]], grad_fn=<SigmoidBackward0>)

In [36]:
model.linear.weight

Parameter containing:
tensor([[ 0.0202,  0.0458, -0.3027,  0.3353, -0.0964]], requires_grad=True)

In [38]:
model.linear.bias

Parameter containing:
tensor([-0.3479], requires_grad=True)

In [40]:
!pip install torchinfo
  

#  from torchinfo module we can find the summary of the network

In [43]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

###### now we will create a new network with hidden layer in which input layer ->5 ,